---
- name: Adding apt key
  become: true
  become_user: root
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3F32EE77E331692F
- name: Apt/deb installing {{ rstudio_tmp_pkg }}...
  become: true
  become_user: root
  ansible.builtin.apt:
    deb: '{{ rstudio_tmp_pkg }}'
    state: present
