---
- name: Trust rpm key
  ansible.builtin.rpm_key:
    state: present
    key: '{{ role_path }}/files/rstudio-signing.key'
- name: Installing {{ rstudio_tmp_pkg }}...
  become: true
  become_user: root
  ansible.builtin.rpm:
    name: '{{ rstudio_tmp_pkg }}'
    state: present
