---
- name: andrewrothstein.epel
  version: v1.1.10
- name: andrewrothstein.git
  version: v3.2.10
- name: andrewrothstein.gcc_toolbox
  version: 2.0.5
- name: andrewrothstein.temurin
  version: 1.4.1
- name: andrewrothstein.r
  version: v2.0.1
